### ISSUE TITLE
Recommendations should be documented

### ISSUE THREAD

**Issue by cgohil8** [OHBA-analysis/osl#105]
This issue is to help us keep track of documentation that should be added somewhere.

**Comment by cgohil8** [comment]
Preprocessing:

For Elekta/MEGIN preproc, recommendation is to run bad chan and segment detection separately on the grads and the mags.

- bad_channels: {picks: 'mag', significance_level: 0.1}
- bad_channels: {picks: 'grad', significance_level: 0.1}
- bad_segments: {segment_len: 600, picks: 'mag', significance_level: 0.1} 
- bad_segments: {segment_len: 600, picks: 'grad', significance_level: 0.1} 

For CTF preproc, beware the reference axial grads being mixed in with the axial grads. The way MNE seems to differentiate these is a bit odd. I.e.
picks: ‘grad’ - selects just the reference axial grads.
picks: 'mag', ref_meg: False - selects just the actual axial grads.
picks: ‘mag’ - selects both reference and actual axial grads.

 Hence, recommendation is to run bad chan and segment detection separately  on the actual actual and reference axial grads. E.g.

- bad_channels: {picks: 'mag', ref_meg: False, significance_level: 0.1}
- bad_channels: {picks: 'grad', significance_level: 0.1}
- bad_segments: {segment_len: 600, picks: 'mag', ref_meg: False, significance_level: 0.1}
- bad_segments: {segment_len: 600, picks: ‘grad’, significance_level: 0.1}

**Comment by cgohil8** [comment]
Add recommended maxfilter settings as the following?

`osl_maxfilter input_files.txt /path/to/output/dir --maxpath /neuro/bin/util/maxfilter --scanner Neo --tsss --mode multistage --headpos —movecomp`

**Comment by matsvanes** [comment]
This is handled in #119
