### ISSUE TITLE
maxfilter.py Import Error

### ISSUE THREAD

**Issue by Kohliver** [OHBA-analysis/osl#109]
When running maxfilter.py the following error occurs:

 `Traceback (most recent call last):
  File "indir/maxfilter/maxfilter.py", line 14, in <module>
    from ..utils import validate_outdir, add_subdir
ImportError: attempted relative import with no known parent package`

Also there are no validate_outdir & add_subdir functions in utils.

Thanks!

**Comment by cgohil8** [comment]
@Kohliver I think this is resolved now (with the merge above). Let me know if it isn't.
