### ISSUE TITLE
fix_sign_ambiguity appears before coreg, beamform_and_parcellate in the config workflow report plot

### ISSUE THREAD

**Issue by woolrich** [OHBA-analysis/osl#132]
In recon report, when coreg and beamform_and_parcellate are run using run_src_batch, followed by running fix_sign_ambiguity in a separate call to run_src_batch (which typically needs to be done separately so that the template subject can be chosen), then the sign flipping erroneously appears before coreg and beamform_and_parcellate in the workflow plot found on the config tab of recon/report/summary_report.html.

Example code:
 
    config = """
        source_recon:
        - coregister:
            include_nose: false
            use_nose: false
            use_headshape: true
            model: Single Layer
            already_coregistered: true
        - beamform_and_parcellate:
            freq_range: [4, 40]
            chantypes: mag
            rank: {mag: 100}
            parcellation_file: fmri_d100_parcellation_with_PCC_reduced_2mm_ss5mm_ds8mm.nii.gz
            method: spatial_basis
            orthogonalisation: symmetric
    """

    source_recon.run_src_batch(
        config,
        src_dir=recon_dir,
        subjects=subjects,
        preproc_files=preproc_fif_files,
        smri_files=smri_files,
    )

    # Find a good template subject to align other subjects to
    template = source_recon.find_template_subject(
        recon_dir, subjects, n_embeddings=15, standardize=True
    )

    config = f"""
        source_recon:
        - fix_sign_ambiguity:
            template: {template}
            n_embeddings: 15
            standardize: True
            n_init: 3
            n_iter: 2500
            max_flips: 20
    """

    # Do the sign flipping
    source_recon.run_src_batch(config,
                               recon_dir,
                               subjects,
                               )

**Comment by cgohil8** [comment]
@woolrich, I think your OPM example script should reproduce this error. Is this data:

https://github.com/OHBA-analysis/osl/blob/main/examples/notts_movie_opm/prepare_parcel_ts.py#L41

available on BMRC or hbaws?

**Comment by cgohil8** [comment]
@woolrich, I was unable to reproduce this bug with the latest code. If you encounter this again, please reopen the issue.
