### ISSUE TITLE
Rogue dirs in the preprocessing report directory cause an error

### ISSUE THREAD

**Issue by woolrich** [OHBA-analysis/osl#140]
If there are rogue dirs in the preprocessing report directory then this line:

https://github.com/OHBA-analysis/osl/blob/1b60ab334f9fbabd86bfc4849cbb8d0f6b343775/osl/report/raw_report.py#L260

means that the ensuing report code will attempt to generate a report using that dir.

**Comment by cgohil8** [comment]
In the scenario:
- Run preproc or source recon for subjects 1-5. This creates the sub-directories for subject 1-5 in the `/report` directory.
- Re-run preproc/source recon for subject 2. This updates the files in the subject 2 sub directory in the `/report` directory.
You want the report to still contain subjects 1-5 but with the updated preproc/source recon for subject 2. The way this is handled is `gen_html_summary` looks up all the sub directories in the `/report` directory.

@woolrich, in what scenario do you generate rogue directories in `/report`?

**Comment by cgohil8** [comment]
Discussed with @woolrich, @matsvanes. Decided we will leave it as it is and explain how the report directories work in the documentation/upcoming OSL workshop.
