### ISSUE TITLE
glm.glm_spectrum bug(?)

### ISSUE THREAD

**Issue by yingjoeyzhou** [OHBA-analysis/osl#209]
tried running `osl.glm.glm_spectrum( raw, fmin=1, fmax=45)` and got a warning "TypeError: glm_periodogram() got an unexpected keyword argument 'reg_categorical'"

both osl and sails are on the latest version.

**Comment by cgohil8** [comment]
Just had a look at this. The issue was `sails 1.2.0` was installed locally on Joey's computer, which caused the issue. Upgrading to the latest (`1.4.0`) resolves this.
