### ISSUE TITLE
Funny naming of run_multistage_maxfilter output from --trans stage.

### ISSUE THREAD

**Issue by Kohliver** [OHBA-analysis/osl#210]
When running run_multistage_maxfilter the names of the created output is "HC1_WM_block3_raw_**transsss**.fif" but should be "HC1_WM_block3_raw_**trans**.fif'

In [this line](https://github.com/OHBA-analysis/osl/blob/c035eaced3d70a05c055900f5c541bdf35bf6401/osl/maxfilter/maxfilter.py#L460C1-L460C67) of the run_multistage_maxfilter function the logfile_tag argument could be set to '_trans' to avoid the funny naming.

**Comment by cgohil8** [comment]
Can you provide the call to `run_multistage_maxfilter` that you're using (or full script)?

**Comment by matsvanes** [comment]
More detailed description in #247
