### ISSUE TITLE
Using -trans in maxfilter affects coregistration

### ISSUE THREAD

**Issue by cgohil8** [OHBA-analysis/osl#216]
If you use the `-trans` option during maxfiltering the placement of the polhemus headshape points/fiducials changes in the coregistration. For example:

Coregistering a file called `HC08_rest_tsss.fif` (maxfiltered without `-trans`), we get:
<img width="477" alt="Screenshot 2023-08-23 at 18 54 00" src="https://github.com/OHBA-analysis/osl/assets/53237863/655fe1ec-5c7a-4f3e-9220-2fb4d090661c">

The same subject and structural, however, using the `HC08_rest_tsss_trans.fif` file, we get:
<img width="480" alt="Screenshot 2023-08-23 at 18 54 02" src="https://github.com/OHBA-analysis/osl/assets/53237863/65aa353a-82b4-4eeb-ba8c-2b289fe45d82">

**The head is much closer to the MEG sensors.**

It appears the `meg` to `head` transformation is different in the fif file if you use `-trans` in maxfiltering, this can be verified with
```
import mne

# Maxfiltered without -trans
info = mne.io.read_info("HC08_rest_tsss.fif")
trans = mne.transforms._get_trans(info["dev_head_t"], "meg", "head")
print(trans)

# Maxfiltered with -trans
info = mne.io.read_info("HC08_rest_tsss_trans.fif")
trans = mne.transforms._get_trans(info["dev_head_t"], "meg", "head")
print(trans)
```

**Comment by cgohil8** [comment]
It appears the `meg` to `head` transformation is different in the fif file if you use `-trans` in maxfiltering:
```
import mne

# Maxfiltering without -trans
info = mne.io.read_info("HC08_rest_tsss.fif")
print(mne.transforms._get_trans(info["dev_head_t"], "meg", "head")

# Maxfilter with -trans
info = mne.io.read_info("HC08_rest_tsss_trans.fif")
print(mne.transforms._get_trans(info["dev_head_t"], "meg", "head")
```

**Comment by cgohil8** [comment]
Still and issue. Probably not resolvable in the code. The advice is use the `_tsss.fif` file. This is what's included in the oxford example scripts: https://github.com/OHBA-analysis/osl/tree/examples/examples/oxford.

**Comment by matsvanes** [comment]
Add warning in the coreg log that the head position might look off whenever `trans` is used, but this does not affect the source data
