### ISSUE TITLE
[preproc] bad channel detection does not mark channels with low variance

### ISSUE THREAD

**Issue by matsvanes** [OHBA-analysis/osl#217]
Anecdotally, the bad channel detection does not mark channels with very low variance (e.g., silent channels). @scho97 has experienced this - @scho97 could you please tell us where to find example data where this is the case?

I thought this might be because bad channel detection only looks for high variance, not low, but that doesn't seem to be the case:
https://github.com/OHBA-analysis/osl/blob/main/osl/preprocessing/osl_wrappers.py#L214
`gesd_args` does not include `outlier_side` as an argument, and the default for this variable is 0 (https://gitlab.com/sails-dev/sails/-/blob/master/sails/utils.py#L186). 

@scho97 Have you played around with different thresholding? Are these picked up when using `outlier_side=-1` (might have to hack around in the code to see)?

**Comment by scho97** [comment]
@matsvanes Thanks for opening this issue. I think this problem occurs in EEG datasets in general. Some data you can use as an example are C1019, P1010, P1030 in NTAD.

I did try detecting bad channels after increasing the threshold from 0.05 to 0.1 (i.e., `bad_channels: {..., significance_level: 0.1}`), but this did not change the results much. I haven't debugged the `gesd` function in `sails` yet.

However, one explanation would be that even if `outlier_side` is set to 0, if we look at how it is implemented
```
elif outlier_side == 0:
       rm_idx[j] = int(np.nanargmax(abs(temp-np.nanmean(temp))))
       R[j] = np.nanmax(abs(temp-np.nanmean(temp)))
```
we can see that absolute values are taken to detect both small and large outliers. However, as our default `metric_func` we are using is `np.std()`, this amounts to selecting only the channels with high variance. So I think you are correct that current bad channel detection only looks for high variance.

**Comment by matsvanes** [comment]
Thanks @scho97! Do you have suggestions on how to improve this?

**Comment by scho97** [comment]
@matsvanes I looked at the code again, and it seems like I have mistaken. The code does catch bad channels of low variance, as it takes absolute values of the deviate from the mean. Sorry for the confusion.

Given this, I think one possible thing we can try is to adjust `p_out` in `gesd_args` to adjust the maximum number of outliers the G-ESD algorithm detects. The current default is 10% of a dataset.

However, in my experience, bad channels were often missed in a relatively few subjects, so I think adjusting `p_out` may result in removing unnecessary channels. The manual removal seemed to be a safer choice in my cases so far.

**Comment by matsvanes** [comment]
Thank you for looking into this further. Does this mean we can close this issue then?
