### ISSUE TITLE
maxfilter logfile issue

### ISSUE THREAD

**Issue by LPNC-LANG** [OHBA-analysis/osl#279]
Hi, 

For some reason I'm having trouble implementing maxfiltering on my data.  Here is an example with only one fif file.
The module outputs an empty sss logfile (0 octet) which obviously throws out an error:

![Capture d’écran du 2024-03-18 14-12-58](https://github.com/OHBA-analysis/osl/assets/130466949/f8ca687a-1176-45bd-802b-a646d177ffa8)

**Comment by cgohil8** [comment]
Is `$HOME/Bureau/osl/osl/maxfilter` the path to the OSL python package maxfilter directory?

**Comment by LPNC-LANG** [comment]
Yes. I followed the installation procedure for a linux machine

**Comment by cgohil8** [comment]
I see, the `--maxpath` argument should actually point to an executable for the Elekta MaxFilter software. This normally comes with your scanner. It's something that needs to be installed outside of OSL. You need a license to use this software.

Alternatively, you can use MNE's implementation of MaxFilter: https://mne.tools/stable/generated/mne.preprocessing.maxwell_filter.html. You will need calibration and cross talk files for your scanner to use this.

However, I see you're trying to MaxFilter the CamCAN dataset. CamCAN, actually provides a version of the MEG data that has already been MaxFiltered. I would **strongly** advise you use the data that has already been MaxFiltered by Cambridge. Then you can go straight to the preprocessing step (i.e. skip the maxfiltering script).

**Comment by LPNC-LANG** [comment]
Thanks for your help. I was also considering using the already-maxfiltered data anyway.
