### ISSUE TITLE
report improvements

### ISSUE THREAD

**Issue by matsvanes** [OHBA-analysis/osl#310]
Keep track of some small improvements in the report functions.

[x] Save the "extra_funcs" as text in the data.pkl file, rather than in a .txt file (i.e., display it the same way we're displaying the logs right now). 
[x] The raw/src summary reports contain interactive tables (from pandas dataframe). Make them start counting at index 1 (rather than 0) for correspondence with the subject reports
[x] Summary report: add tab for all error log files (might have to explicitly delete old files when starting a log)
[x] Add date+time to error reports
[x] Navigation: fix navigating using arrow keys
[x] Navigation: fix saving the current tab when going to a different session
[x] Soure report: In sign flipping, rather than showing the table with values of different iterations, show the best value over iterations for each session

**Comment by cgohil8** [comment]
Do we have some example data (e.g. on hbaws) to test the report generation with?

**Comment by matsvanes** [comment]
> Do we have some example data (e.g. on hbaws) to test the report generation with?

I have some in `/ohba/pi/mwoolrich/mvanes/enh/` (can you access that?), but not yet for the subject source report. 

Note that I already did quite a bit of the above - I'll push that branch to here shortly

**Comment by matsvanes** [comment]
> Summary report: add tab for all error log files (might have to explicitly delete old files when starting a log)
I chose to not remove old error files, because I don't think removing files as a default option is a good idea. But it would be helpful if the error logs have a date/time in there the way other log files have, e.g.
`[2024-07-03 17:19:43]  - INFO - osl.logger:122 : OSL osl_logger: handler 'console' level set to 'INFO'`
That way it's easy to recognise when an error log is older than the latest preproc/src log. Another option is to - in case an error log already exists and we rerun the preproc/src proc chain, something is added to the error log indicating that it's not about the latest process. 
What do you think @cgohil8 ?

**Comment by matsvanes** [comment]
Also, if @cgohil8 could test the src report, that'd be great :)

**Comment by cgohil8** [comment]
Not sure the source report 'extra functions' feature is working.

<img width="773" alt="Screenshot 2024-07-13 at 19 35 11" src="https://github.com/user-attachments/assets/f13c9ead-1806-4a6f-9ce0-1141ef17f97e">

**Comment by matsvanes** [comment]
I fixed the above in https://github.com/OHBA-analysis/osl/pull/311/commits/50d5e981b530e35ac2b6fd0b6216b8cec805f70d
