### ISSUE TITLE
Debugging line left in documentation

### ISSUE THREAD

**Issue by cgohil8** [OHBA-analysis/osl#332]
Don't know if this was left intentionally, but looks like there's a line left in the documentation that might have been added when testing/debugging. It says

> Hello here we are then

See below.

![Screenshot 2024-08-22 at 16 22 22](https://github.com/user-attachments/assets/919848f3-433c-488b-a41c-6ce0d26ee325)

**Comment by matsvanes** [comment]
Fixed in https://github.com/OHBA-analysis/osl/pull/351
