### ISSUE TITLE
src_recon batch fails with extra funcs

### ISSUE THREAD

**Issue by matsvanes** [OHBA-analysis/osl#343]
source_recon batch processing with supplied `extra_funcs` fails when no default input parameters are specified:

https://github.com/OHBA-analysis/osl/blob/main/osl/source_recon/batch.py#L204
```
args, _, _, defaults = inspect.getargspec(func)
args_with_defaults = args[-len(defaults):]
```

suggested fix:
`args_with_defaults = args[-len(defaults):] if defaults is not None else []`

What do you think @cgohil8 ?

**Comment by cgohil8** [comment]
Looks fine, if you tested that with/without other functions in the source config and it works, go for it.

**Comment by matsvanes** [comment]
Fixed.
